###

POST http://localhost:9000/api/movies HTTP/1.1
Content-type: application/json

{
    "title": "Iron Man 2",
    "year": 2008,
    "mov_time": 126,
    "mov_lang": "English",
    "mov_dt_rel": "28-04-2010",
    "mov_rel_country": "Chile"
}




###

GET http://localhost:9000/api/movies HTTP/1.1



###
GET http://localhost:9000/api/movies/63f3ebae0dd2c0ced265beb8 HTTP/1.1


###

PUT http://localhost:9000/api/movies/63f3ebae0dd2c0ced265beb8 HTTP/1.1
Content-type: application/json

{
    "title": "Lost in Translation",
    "year": 2003,
    "mov_time": 105,
    "mov_lang": "English",
    "mov_dt_rel": "03-10-2003   ",
    "mov_rel_country": "Estados Unidos"
}


###

DELETE  http://localhost:9000/api/movies/63f4ca0f4fdb39c22173ac29 HTTP/1.1