###

POST http://localhost:9000/api/mcast HTTP/1.1
Content-type: application/json

{  
    "act_id": 9,
    "mov_id": 11,
    "role": "Spiderman"
    
}


###

GET http://localhost:9000/api/mcast HTTP/1.1



###
GET http://localhost:9000/api/mcast/63f6a0bacc1694d22e8beea7 HTTP/1.1


###

PUT http://localhost:9000/api/mcast/63f6a0bacc1694d22e8beea7 HTTP/1.1
Content-type: application/json

{
    "act_id": 5,
    "mov_id": 1,
    "role": "Tony Stark"
   
}



###

DELETE  http://localhost:9000/api/mcast/63f7c5b5c2e4866c4af11ce4 HTTP/1.1


