###

POST http://localhost:9000/api/mgenres HTTP/1.1
Content-type: application/json

{
    "mov_id": 14,
    "gen_id": 21        
}

###

GET http://localhost:9000/api/mgenres HTTP/1.1



###
GET http://localhost:9000/api/mgenres/63f7d1a084cae9850ec12c56 HTTP/1.1


###

PUT http://localhost:9000/api/mgenres/63f7d1a084cae9850ec12c56 HTTP/1.1
Content-type: application/json

{
    "mov_id": 11,
    "gen_id": 11     
}



###

DELETE  http://localhost:9000/api/mgenres/63f7d29b84cae9850ec12c62 HTTP/1.1


