###

POST http://localhost:9000/api/reviewer HTTP/1.1
Content-type: application/json

{   
    "rev_id": 3,
    "rev_name": "German"
    
}

###

GET http://localhost:9000/api/reviewer HTTP/1.1

###
GET http://localhost:9000/api/reviewer/63f7a414030f0bcf9228dc25 HTTP/1.1

###

PUT http://localhost:9000/api/reviewer/63f7a414030f0bcf9228dc25 HTTP/1.1
Content-type: application/json

{   
    "rev_id": 2,
    "rev_name": "TheCounterFilm"
    
}

###

DELETE  http://localhost:9000/api/reviewer/63f7a7b787ed9a293301cb90 HTTP/1.1


