###

POST http://localhost:9000/api/mcast HTTP/1.1
Content-type: application/json

{   "act_id": 10,
    "mov_id": 10,
    "role": "KKKKK"
    
}


###

GET http://localhost:9000/api/mcast HTTP/1.1



###
GET http://localhost:9000/api/mcast/63f6a0bacc1694d22e8beea7 HTTP/1.1


###

PUT http://localhost:9000/api/mcast/63f6a0bacc1694d22e8beea7 HTTP/1.1
Content-type: application/json

{
    "act_id": 5,
    "mov_id": 1,
    "role": "Tony Starkkk"
   
}



###

DELETE  http://localhost:9000/api/mcast/63f6a101cc1694d22e8beeae HTTP/1.1


